# Neural Network from Scratch only using Numpy
Using only Numpy. No sckit learn, no pytorch.

### Given:
- Two layer NN
- 3 neurons One hidden layer with ReLu activation 
- 1 neuron one output layer with sigmoid activation 
- X is [1,2]
- Parameters: W1,B1,W2,B2

### Task: 
- Implementing forward pass : calculating z1,a1,z2,a2
- Implementing backpropogation: calculating gradient wrt to the four parameters
- Running gradient descent update
- Checking results




In [ ]:
import numpy as np


ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [57]:
X = np.array([[1],[2]])
W1 = np.array([[0.1,0.2],[-0.3,0.4],[0.5,-0.1]])
B1 = np.array([[0.1],[-0.2],[0.3]])
W2 = np.array([0.3,-0.2,0.5])
B2 = np.array([0.1])
print("W1", W1)
print("W2",W2)
print("B1",B1)
print("B2",B2)

W1 [[ 0.1  0.2]
 [-0.3  0.4]
 [ 0.5 -0.1]]
W2 [ 0.3 -0.2  0.5]
B1 [[ 0.1]
 [-0.2]
 [ 0.3]]
B2 [0.1]


## 1. Forward Pass

In [58]:
#Hidden Layer 
Z1 = (np.dot(W1,X))+B1
Z1

array([[0.6],
       [0.3],
       [0.6]])

In [59]:
## ReLu Activaction
A1 = np.where(Z1<0,0,Z1)
A1


array([[0.6],
       [0.3],
       [0.6]])

In [62]:
#Output Layer
Z2 = (np.dot(W2,A1))+B2
Z2

array([0.52])

In [67]:
#Sigmoid Activation
A2 = Z2
for i in range(len(A2)):
    ez = np.exp(A2[i])
    A2[i] = ez/(1+ez)
print("y predicted =", A2)

y predicted = [0.65742553]


## 2.Backward pass: Gradient Calc

Now we go step by step in reverse and compute gradients
