# Neural Network from Scratch only using Numpy
Using only Numpy. No sckit learn, no pytorch.

### Given:
- Two layer NN
- 3 neurons One hidden layer with ReLu activation 
- 1 neuron one output layer with sigmoid activation 
- X is [1,2]
- Parameters: W1,B1,W2,B2

### Task: 
- Implementing forward pass : calculating z1,a1,z2,a2
- Implementing backpropogation: calculating gradient wrt to the four parameters
- Running one gradient descent update
- Checking results




In [184]:
import numpy as np


In [185]:
X = np.array([[1],[2]])
W1 = np.array([[0.1,0.2],[-0.3,0.4],[0.5,-0.1]])
B1 = np.array([[0.1],[-0.2],[0.3]])
W2 = np.array([[0.3,-0.2,0.5]])
B2 = np.array([0.1])
print("W1", W1)
print("W2",W2)
print("B1",B1)
print("B2",B2)

W1 [[ 0.1  0.2]
 [-0.3  0.4]
 [ 0.5 -0.1]]
W2 [[ 0.3 -0.2  0.5]]
B1 [[ 0.1]
 [-0.2]
 [ 0.3]]
B2 [0.1]


## 1. Forward Pass

In [186]:
#Hidden Layer 
Z1 = (np.dot(W1,X))+B1
Z1

array([[0.6],
       [0.3],
       [0.6]])

In [187]:
## ReLu Activaction
A1 = np.where(Z1<0,0,Z1)
A1


array([[0.6],
       [0.3],
       [0.6]])

In [188]:
#Output Layer
Z2 = (np.dot(W2,A1))+B2
Z2

array([[0.52]])

In [189]:
#Sigmoid Activation
A2 = Z2.copy()
for i in range(len(A2)):
    A2 = 1 / (1 + np.exp(-Z2))
    #ez = np.e**A2[i]
    #A2[i] = ez/(1+ez)
y_predicted = A2
L = -1*np.log(y_predicted)
print("y predicted = ", y_predicted)
print("Loss = ",L)

y predicted =  [[0.62714777]]
Loss =  [[0.46657309]]


## 2.Backward pass: Gradient Calc

Now we go step by step in reverse and compute gradients


In [190]:
#Since L = -1*log(Ypredicted)
LwrtY = -1/y_predicted

#LwrtZ2 = LwrtY*YwrtZ2
Y = 1
YwrtZ2 =   Y - y_predicted
#LwrtW2 = LwrtZ2*Z2wrtW2
Z2wrtW2 = A1.T
LwrtW2 = np.dot(LwrtZ2,Z2wrtW2)

#LwrtB2 = LwrtZ2*Z2wrtB2
Z2wrtB2 = 1
LwrtB2 = np.dot(LwrtZ2,Z2wrtB2)

#LwrtA1 = LwrtZ2*Z2wrtA1
Z2wrtA1 = W2.T
LwrtA1 = np.dot(Z2wrtA1,LwrtZ2)

#LwrtZ1 = LwrtA1*A1wrtZ1 :ReLu Activation
A1wrtZ1 = np.where(Z1>0,1,0)
LwrtZ1 = LwrtA1*A1wrtZ1

#LwrtW1 = LwrtZ1*Z1wrtW1
Z1wrtW1 = X
LwrtW1 = np.dot(LwrtZ1,Z1wrtW1.T)

#LwrtB1 = LwrtZ1*Z1wrtB1
Z1wrtB1 = 1
LwrtB1 = LwrtZ1*Z1wrtB1

print("L_wrt_Y = ",LwrtY)
print("L_wrt_Z2 = ",LwrtZ2)
print("L_wrt_W2 = ",LwrtW2)
print("L_wrt_B2 = ",LwrtB2)
print("L_wrt_A1 = ",LwrtA1)
print("L_wrt_Z1 = ",LwrtZ1)
print("L_wrt_W1 = ",LwrtW1)
print("L_wrt_B1 = ",LwrtB1)


L_wrt_Y =  [[-1.59452055]]
L_wrt_Z2 =  [[-0.37285223]]
L_wrt_W2 =  [[-0.22371134 -0.11185567 -0.22371134]]
L_wrt_B2 =  [[-0.37285223]]
L_wrt_A1 =  [[-0.11185567]
 [ 0.07457045]
 [-0.18642612]]
L_wrt_Z1 =  [[-0.11185567]
 [ 0.07457045]
 [-0.18642612]]
L_wrt_W1 =  [[-0.11185567 -0.22371134]
 [ 0.07457045  0.14914089]
 [-0.18642612 -0.37285223]]
L_wrt_B1 =  [[-0.11185567]
 [ 0.07457045]
 [-0.18642612]]


### Value check: 
Values match wtih manually calculated values

## 3. Running gradient descent update

Updating W2 with alpha = 0.1

In [191]:
alpha = 0.1
# W2 = W2 - alpha(L_wrt_W2)
W2 = W2 - 0.1*(LwrtW2)

In [192]:
W2

array([[ 0.32237113, -0.18881443,  0.52237113]])

### Updated Values check: 
Values match wtih manually calculated values